### ISSUE TITLE
pubmed不能显示分区及影响因子

### ISSUE THREAD

**Issue by shmilyruru** [naivenaive/EasyPubMed#1]
今日pubmed不能显示分区及影响因子，单独进入后可查看，不知可否解决

**Comment by naivenaive** [comment]
已接到目前搜索页面无法正常显示影响因子和分区的报告。从原代码看近日pubmed网站又对部分代码进行了更新，造成目前插件无法正常显示的问题。主要由于一个标签原为labs-docsum-journal-citation full-journal-citation关键项目被pubmed调整为docsum-journal-citation full-journal-citation所致。目前我正试图修复，但由于本人身体原因近期可能无法很快上传修改后版本，望理解。我会尽快提交修复后版本，最晚月末可以正常使用。

**Comment by naivenaive** [comment]
在Version 0.0.4版本中已修复2020/7/17 由于Pubmed网站更新所致无法显示IF、JCR及CAS分区的问题，目前可以使用开发者模式运行使用Version 0.0.4版本。Version 0.0.4版本已上传至chrome及Edge应用商店审核将于近期上线，欢迎关注。更多功能正在开发中，欢迎您反馈并提出宝贵建议。
