### ISSUE TITLE
关于全屏显示全文PDF功能异常

### ISSUE THREAD

**Issue by eccwy98** [naivenaive/EasyPubMed#10]
全屏显示全文PDF功能在Chrome版本 92.0.4515.131发生异常，无法如常在chrome页面上正常打开全文，而是弹出新页面后自动删除页面，麻烦跟进，谢谢

**Comment by naivenaive** [comment]
你好，近期scihub及libgen进行了更新，目前0.1.8版本已经修复，如有其他问题欢迎联系
