### ISSUE TITLE
是的，翻译功能不能使用了

### ISSUE THREAD

**Issue by 18281616707** [naivenaive/EasyPubMed#12]

**Comment by naivenaive** [comment]
近日翻译功能无法正常使用，原因如下：translate.google.cn不再提供翻译接口，而是自动跳转到translate.google.com，而后者国内无法正常访问。目前解决办法：请使用代理服务器，或点击翻译前方'G'按键跳转到翻译界面查看翻译结果。开发团队正在积极寻找翻译替代解决方案，如果有免费好用的翻译接口提供，欢迎联系easypubmed.project@gmail.com
