### ISSUE TITLE
sci-hub站点选择受限

### ISSUE THREAD

**Issue by Xiaochen-Zhang99** [naivenaive/EasyPubMed#2]
sci-hub站点选择只能选择给定的两个网站，但是这两个网站都经常登不上，而sci-hub.ren这个比较稳定，是否可以取消网站选择限制？

**Comment by naivenaive** [comment]
感谢您的建议，目前EasyPubMed允许的sci-hub URL共四个，分别为https://sci-hub.st/，https://sci-hub.se/，https://sci-hub.ee/，
https://sci-hub.tw/。这四个sci-hub url来源于lovescihub twitter推荐的网址，您可以在这四个URL中切换。由于完全开放让使用者随意更换sci-hub网址会使程序后台的权力过大，有可能无法通过chrome及edge商店的审查。我会在后续测试后开放sci-hub.ren这一URL，感谢您的反馈。

**Comment by naivenaive** [comment]
在Version 0.0.4中已支持支持https://sci-hub.ren作为sci-hub URL，更多功能正在设计添加，欢迎进一步反馈建议。
