### ISSUE TITLE
一个小建议，建议优化一下影响因子筛选结合Pubmed的时间筛选

### ISSUE THREAD

**Issue by TrumanZYX** [naivenaive/EasyPubMed#4]
我使用了影响因子筛选和发布日期排序，之后出现问题：
会出现一页就只有1篇文章，感觉是将每一页的符合条件文章筛选出来，希望能直接一下子自动排序，就是将很多不同页的文献都排序到一页，十分感谢您的软件

**Comment by naivenaive** [comment]
你好。感谢反馈。当激活过滤器后再点击’Show More‘按钮后会自动对加载的文献进行筛选。由于后面展示文章一般影响因子及分区较低，这时会出现每页仅有一篇文章被筛选出来的情况。点击“Deactivate EasyPubMed Filter”可以恢复到默认展示模式。由于PubMed并未提供根据影响因子进行排序的选项，因此过滤功能只能根据所展示文章影响因子进行筛选。由于每次点击“Show More”后文章会出现很大的变动，根据影响因子排序会导致后面的文章出现在排序中前面，这回影响使用，因此并没有制作自动排序的功能。
