### ISSUE TITLE
检验可以选择谷歌翻译还是百度翻译

### ISSUE THREAD

**Issue by IamTonyMa** [naivenaive/EasyPubMed#5]
谷歌翻译感觉不稳定，有时候会刷新不出来。

**Comment by naivenaive** [comment]
国内对于谷歌使用屏蔽的。有时google翻译会慢一些。文字翻译目前基本没有免费的服务。目前EasyPubMed所采用的翻译也是对谷歌翻译API破译后所得结果，百度翻译是否提供可被破译的免费接口我需要进一步研究。谢谢你的反馈。
