### ISSUE TITLE
更改工具条位置

### ISSUE THREAD

**Issue by ayue2019** [naivenaive/EasyPubMed#6]
在使用PubMed查找文献时，工具条距离标题略远，影响因子等信息仿佛是下一个标题的，在单条文献显示界面，中间隔了很长一段摘要，不利于信息获取，有没有可能移动下工具条的位置？如下图所示：

![无标题](https://user-images.githubusercontent.com/58946586/106153334-67029a80-61b9-11eb-832d-1e1241ca56e8.png)
![无标题1](https://user-images.githubusercontent.com/58946586/106153345-6964f480-61b9-11eb-93ca-d0e1aefebd83.png)

**Comment by naivenaive** [comment]
感谢你的提议，目前工具条位置是根据老版本PubMedy插件设置的，我会征求更多人的意见，以使插件更好用。谢谢你的反馈。
