### ISSUE TITLE
每页显示多余10条filter就不能用了

### ISSUE THREAD

**Issue by xiaoaozqd** [naivenaive/EasyPubMed#8]
十分感谢您开发的插件，用起来很方便，只是有的时候检索的文献太多事想用filter，但是一旦每页多余10个的时候就没法用了，需要不停的点击加载更多，如果能把这个限制再解除一下就更好了。

**Comment by naivenaive** [comment]
感谢使用。你可以在PubMed搜索界面Display Options选项中，将per page修改为50，100或更多。这样每次加载就会出现更多得文献，减少点击加载更多得次数
