### ISSUE TITLE
英文界面下行会乱

### ISSUE THREAD

**Issue by mixian95** [naivenaive/EasyPubMed#9]
你好！插件非常棒！但是我在英文下界面会乱，麻烦问一下怎么解决，谢谢！![image](https://user-images.githubusercontent.com/67423851/126057832-36db5b6c-e2aa-4c46-8d3e-b082810e1a5f.png)

**Comment by mixian95** [comment]
chrome浏览器，商店安装的17版

**Comment by naivenaive** [comment]
你好，界面字体的问题，请问你有安装其他插件修改屏幕字体吗？

**Comment by mixian95** [comment]
> 你好，界面字体的问题，请问你有安装其他插件修改屏幕字体吗？

更新最新版后已经正常啦！感谢！
